<?php

/**
* @file islandora_common_utilities.module
* TODO: Enter file description here.
*/

/**
* Form builder.
*/
function islandora_common_utilities_settings_form($form, &$form_state) {
$form['islandora_common_utilities_variable_foo'] = array(
'#type' => 'textfield',
'#title' => t('Foo'),
'#default_value' => variable_get('islandora_common_utilities_variable_foo', 42),
'#required' => TRUE,
);

// TODO! You probably don't need validation or submit handlers if using system_settings_form().
return system_settings_form($form);
}

/**
* Form validate handler.
*/
function islandora_common_utilities_settings_form_validate($form, &$form_state) {
if ($form_state['values']['element'] != 'hello') {
form_set_error('element', t('Please say hello?'));
}
}

/**
* Form submit handler.
*/
function islandora_common_utilities_settings_form_submit($form, &$form_state) {

}

/**
* Implements hook_menu().
*/
function islandora_common_utilities_menu() {
$items = array();

$items['admin/config/islandora_common_utilities'] = array(
'title' => 'Administer Islandora Common Utilities',
'page callback' => 'drupal_get_form',
'page arguments' => array('islandora_common_utilities_settings_form'),
'access arguments' => array('administer islandora_common_utilities'),
);
return $items;
}